
name: Mirror repo to S3
"on":
  push:
    branches:
      - main
jobs:
  s3Backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: S3 Backup
        uses: DesktopMetal/dm-s3-backup@v1
        env:
          ACCESS_KEY_ID: ${{ secrets.S3_BAK_AK }}
          SECRET_ACCESS_KEY: ${{ secrets.S3_BAK_PASS }}
          MIRROR_TARGET: dm-github-backup/s3rver/
        with:
          args: --overwrite --remove
